version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - visual-product-db:/data/db
    restart: unless-stopped

volumes:
  visual-product-db:
