import os
from dotenv import load_dotenv

load_dotenv()  # load from .env

SHOE_IMAGES_FOLDER = os.getenv("SHOE_IMAGES_FOLDER")
TEST_SET_MODIFY_FOLDER= os.getenv("TEST_SET_MODIFY_FOLDER")

FAISS_INDEX_PATH = os.getenv("FAISS_INDEX_PATH")
CLIP_FAISS_INDEX_PATH = os.getenv("CLIP_FAISS_INDEX_PATH")
CLIP_FAISS_INDEX_TEXT_PATH = os.getenv("CLIP_FAISS_INDEX_TEXT_PATH")

SHOE_PRODUCT_JSON_PATH=os.getenv("SHOE_PRODUCT_JSON_PATH")
IMAGE_PATHS_JSON=os.getenv("IMAGE_PATHS_JSON")

FAISS_HYBRID_INDEX_PATH = os.getenv("FAISS_HYBRID_INDEX_PATH")
EMBEDDING_META_HYBRID_INDEX=os.getenv("EMBEDDING_META_HYBRID_INDEX")
KMEANS_MODEL_PATH=os.getenv("KMEANS_MODEL_PATH")

EMBEDDING_CLIP_FAISS_METADATA_COLLECTION = os.getenv("EMBEDDING_CLIP_FAISS_METADATA_COLLECTION")
EMBEDDING_CNN_FAISS_METADATA_COLLECTION= os.getenv("EMBEDDING_CNN_FAISS_METADATA_COLLECTION")
PRODUCT_COLLECTION = os.getenv("PRODUCT_COLLECTION")

EMBEDDING_CLIP_TEXT_FAISS_METADATA_COLLECTION= os.getenv("EMBEDDING_CLIP_TEXT_FAISS_METADATA_COLLECTION")

gemini_api_key = os.getenv("GEMINI_API_KEY")